# Generated by Django 3.0.5 on 2020-04-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='product_listing.Category'),
        ),
    ]
