# Generated by Django 3.0.5 on 2020-04-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing', '0002_auto_20200421_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='product_listing.Category'),
        ),
    ]
