# Generated by Django 3.0.5 on 2020-04-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing', '0003_auto_20200421_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
