# Generated by Django 3.0.5 on 2020-04-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing', '0005_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_listing.Company'),
            preserve_default=False,
        ),
    ]
