# Generated by Django 3.0.5 on 2020-04-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_listing', '0007_auto_20200422_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
